---
- name: My First playbook
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks:
  - name: Install package
    package:
      name: httpd
      state: installed 

  - name: Install Telnet
    package:
      name: telnet
      state: installed 

  - name: Add Bob
    user:
      name: httpd
      state: absent 

  - name: Add Tom
    user:
      name: tom
      state: present 